[general]
import = [
  "~/.config/alacritty/themes/one_light.toml"
]

[font]
size = 18.0

[font.bold]
family = "SourceCodeVF"
style = "Bold"

[font.normal]
family = "SourceCodeVF"
style = "Regular"

[terminal.shell]
args = ["-c", "zellij attach -c"]
program = "/opt/homebrew/bin/fish"

[window]
startup_mode = "Maximized"
option_as_alt = "Both"

[terminal]

